[Definition]
failregex = ^<HOST>.*"(GET|POST|HEAD) /((wordpress|wp-content|wp-admin|wp-includes|update|blog|old|new|backup|main)|(xmlrpc|contact|themes|readme|htaccess|phpinfo|info|test|env|server-info|php_version|version|setup-config|config|postnews|userfuns|index|log|file|class|about|mail|manager)\.php).*" (302|404|444|403|499|400|500|503) .*$

ignoreregex =
